postprocessor:
  name: advlift
  APS_mode: False
  postprocessor_args:
    temperature: 1
  postprocessor_sweep:
    temperature_list: [1]

adversary:
  name: pgd
  adversary_args:
    alpha: 8  # out of 255
    epsilon: 1  # out of 255, PGD only
    steps: 20  # PGD only
    