postprocessor:
  name: advlift
  APS_mode: False
  postprocessor_args:
    temperature: 1
  postprocessor_sweep:
    temperature_list: [1]

adversary:
  name: pgd    # fgsm, pgd
  common_args:
    label_source: prediction  # ground, prediction
    eps: 8  # overall attack radius, out of 255
  pgd_args:
    step_size: 1  # single step radius, out of 255
    steps: 20
    random_start: true
    